# Generated by Django 3.0.3 on 2020-04-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('category_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=256)),
                ('answer', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('theme_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('Domestic', 'Domestic'), ('International', 'International')], max_length=256)),
                ('destination', models.CharField(max_length=256)),
                ('dst_img', models.ImageField(upload_to='images/')),
                ('vehicle', models.CharField(blank=True, max_length=256)),
                ('tickets', models.CharField(blank=True, max_length=256)),
                ('visa', models.BooleanField()),
                ('note', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('offer', models.PositiveIntegerField(blank=True, null=True)),
                ('popular', models.BooleanField()),
                ('pack_domestic_category', models.ManyToManyField(blank=True, related_name='domestic_category', to='package_app.DomesticCategory')),
                ('pack_international_category', models.ManyToManyField(related_name='international_category', to='package_app.InternationalCategory')),
                ('pack_theme_category', models.ManyToManyField(blank=True, related_name='theme_category', to='package_app.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('package', models.ManyToManyField(related_name='inclusions', to='package_app.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField(unique=True)),
                ('city', models.CharField(max_length=256)),
                ('hotel_img', models.URLField(unique=True)),
                ('star_rating', models.PositiveIntegerField(blank=True)),
                ('package', models.ManyToManyField(related_name='hotels', to='package_app.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('package', models.ManyToManyField(related_name='exclusions', to='package_app.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Daywise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest', models.BooleanField()),
                ('duration', models.CharField(choices=[('0 Night / 1 Day', '0 Night / 1 Day'), ('1 Night / 2 Days', '1 Night / 2 Days'), ('2 Nights / 3 Days', '2 Nights / 3 Days'), ('3 Nights / 4 Days', '3 Nights / 4 Days'), ('4 Nights / 5 Days', '4 Nights / 5 Days'), ('5 Nights / 6 Days', '5 Nights / 6 Days'), ('6 Nights / 7 Days', '6 Nights / 7 Days'), ('7 Night / 8 Days', '7 Night / 8 Days'), ('8 Nights / 9 Days', '8 Nights / 9 Days'), ('9 Nights / 10 Days', '9 Nights / 10 Days'), ('10 Nights / 11 Days', '10 Nights / 11 Days'), ('11 Nights / 12 Days', '11 Nights / 12 Days'), ('12 Nights / 13 Days', '12 Nights / 13 Days')], max_length=256)),
                ('price_adult', models.PositiveIntegerField()),
                ('price_child', models.PositiveIntegerField(blank=True)),
                ('price_infant', models.PositiveIntegerField(blank=True)),
                ('day1', models.TextField()),
                ('day2', models.TextField(blank=True)),
                ('day3', models.TextField(blank=True)),
                ('day4', models.TextField(blank=True)),
                ('day5', models.TextField(blank=True)),
                ('day6', models.TextField(blank=True)),
                ('day7', models.TextField(blank=True)),
                ('day8', models.TextField(blank=True)),
                ('day9', models.TextField(blank=True)),
                ('day10', models.TextField(blank=True)),
                ('day11', models.TextField(blank=True)),
                ('day12', models.TextField(blank=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daywiseschedules', to='package_app.Package')),
            ],
        ),
    ]
