# Generated by Django 3.0.3 on 2020-04-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domesticcategory',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
