# Generated by Django 3.0.3 on 2020-04-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0002_auto_20200421_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='daywise',
            name='day10_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day11_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day12_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day1_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day2_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day3_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day4_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day5_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day6_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day7_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day8_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day9_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
