# Generated by Django 3.0.3 on 2020-04-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0003_auto_20200421_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='daywise',
            name='day13',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day13_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day14',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day14_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day15',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day15_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day16',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day16_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day17',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day17_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day18',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day18_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day19',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day19_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day20',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='daywise',
            name='day20_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='domesticcategory',
            name='popular',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalcategory',
            name='popular',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='popular',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
