# Generated by Django 3.0.3 on 2020-04-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0004_auto_20200423_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
